### ISSUE TITLE
swiftlintの追加

### ISSUE THREAD

**Issue by pakusongi** [ByeongGwan-Seo/PriceTracker_dev#29]
ネットで調べてプロジェクトにswiftlintを追加してください

**Comment by gomserker-jp** [comment]
swiftlintの場合はSPMで導入しようとすると
`SourceKittenFramework/library_wrapper.swift:58: Fatal error: Loading sourcekitdInProc.framework/Versions/A/sourcekitdInProc failed`
エラーが発生しています。
derivedDataの削除、swiftlintの再設置、キャッシュクリアーまで行いましたが、問題が繰り返されているため、対応法を探しています。

**Comment by gomserker-jp** [comment]
レビュー及びマージ済みでクローズします。
